### ISSUE TITLE
ファイルが見つからないためエラーが発生する

### ISSUE THREAD

**Issue by crohas** [miyadaiku/miyadaiku#10]
build-server 起動中に 特定の記事を移動させたり削除すると 以下のようなエラーが発生し、build server が落ちます。

```python
Traceback (most recent call last):
  File "venv/bin/miyadaiku-build", line 11, in <module>
    load_entry_point('miyadaiku==0.0.51', 'console_scripts', 'miyadaiku-build')()
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/scripts/muneage.py", line 211, in main
    code = _main()
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/scripts/muneage.py", line 199, in _main
    build(d, props, args.traceback, miyadaiku.core.DEBUG)
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/scripts/muneage.py", line 120, in build
    site = Site(d, props, traceback, debug)
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/core/main.py", line 81, in __init__
    contents.load_directory(self, path / CONTENTS_DIR)
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/core/contents.py", line 1201, in load_directory
    content = _loader.from_file(site, p, name)
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/core/contents.py", line 1054, in from_file
    body = self._get_body_from_file(site, srcpath, destpath, metadata)
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/core/contents.py", line 1086, in _get_body_from_file
    _metadata, body = rst.load(srcpath, metadata)
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/core/rst.py", line 203, in load
    pub.set_source(source_path=os.fspath(path))
  File "/root/cronote/venv/lib64/python3.6/site-packages/docutils/core.py", line 179, in set_source
    encoding=self.settings.input_encoding)
  File "/root/cronote/venv/lib64/python3.6/site-packages/docutils/io.py", line 247, in __init__
    raise InputError(error.errno, error.strerror, source_path)
docutils.io.InputError: [Errno 2] No such file or directory: '/root/cronote/contents/2018/test/index.rst'
```

エラーになる事自体は問題ないのですが、server が止まってしまうのは少々問題な気がしています。

**Comment by atsuoishimoto** [comment]
ありがとうございます。
修正しました。
