### ISSUE TITLE
コンフィグ以外の用途で置いてあるyaml ファイルでKeyErrorが発生する

### ISSUE THREAD

**Issue by crohas** [miyadaiku/miyadaiku#13]
yaml ファイルは コンフィグとしてみなされるためか、 type キーがないと KeyErrorが発生します。

こちらのエラー自体は既知で、公開したい yaml ファイルは `files/` に置くべきという考えはわかるのですが、(コンフィグとして invalid な)yaml ファイルは無視するようにできないでしょうか。

個人的な事情を話すと、この yaml自体をコンテンツにしたいわけではなく、コンテンツごとに docker-composeで検証環境を作ろうとしたら `docker-compose.yml` をコンフィグとして解析しようとしてエラーになりました。おそらく利用ケースとしてはレアで想定していないとは思うのですが、このようなファイルがあるだけで watch 中に エラーで build がストップしてしまうのが少々つらいです。

以下 watch中に発生したエラーです。

```python
Traceback (most recent call last):
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/core/contents.py", line 1201, in load_directory
    content = _loader.from_file(site, p, name)
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/core/contents.py", line 1056, in from_file
    return self._build_content(site, None, srcpath, dirname, name, metadata, body)
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/core/contents.py", line 1037, in _build_content
    return content_class(metadata['type'])(site, dirname, filename, metadata, body)
KeyError: 'type'
Traceback (most recent call last):
  File "venv/bin/miyadaiku-build", line 11, in <module>
    load_entry_point('miyadaiku==0.0.51', 'console_scripts', 'miyadaiku-build')()
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/scripts/muneage.py", line 211, in main
    code = _main()
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/scripts/muneage.py", line 199, in _main
    build(d, props, args.traceback, miyadaiku.core.DEBUG)
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/scripts/muneage.py", line 120, in build
    site = Site(d, props, traceback, debug)
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/core/main.py", line 81, in __init__
    contents.load_directory(self, path / CONTENTS_DIR)
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/core/contents.py", line 1201, in load_directory
    content = _loader.from_file(site, p, name)
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/core/contents.py", line 1056, in from_file
    return self._build_content(site, None, srcpath, dirname, name, metadata, body)
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/core/contents.py", line 1037, in _build_content
    return content_class(metadata['type'])(site, dirname, filename, metadata, body)
KeyError: 'type'
```

ご検討をお願いします。

**Comment by atsuoishimoto** [comment]
ありがとうございます。
エラーが出るのは仕方ないと思いますが、watchが止まってしまうのはBugですね。後で調べてみます。

**Comment by atsuoishimoto** [comment]
修正しました。
