### ISSUE TITLE
例外オブジェクトの取扱に失敗して build が落ちる

### ISSUE THREAD

**Issue by crohas** [miyadaiku/miyadaiku#9]
画像ファイルなどを `contents/` に配置して利用すると、たまに以下のようなエラーが発生します。

辞書の型が期待と異なるために発生しているものと思われます。

```python
Traceback (most recent call last):
  File "venv/bin/miyadaiku-build", line 11, in <module>
    load_entry_point('miyadaiku==0.0.51', 'console_scripts', 'miyadaiku-build')()
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/scripts/muneage.py", line 211, in main
    code = _main()
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/scripts/muneage.py", line 199, in _main
    build(d, props, args.traceback, miyadaiku.core.DEBUG)
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/scripts/muneage.py", line 122, in build
    code = site.build()
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/core/main.py", line 329, in build
    self._print_err_dict(err)
  File "/root/cronote/venv/lib64/python3.6/site-packages/miyadaiku/core/main.py", line 138, in _print_err_dict
    logger.error(f'  {d["exctype"]}: {d["args"][0].rstrip()}')
AttributeError: 'int' object has no attribute 'rstrip'
```

バグと思われるのでご確認をお願いします。

**Comment by atsuoishimoto** [comment]
これ、再現できないのですが、どんなファイルをどんなファイル名で置くと発生するか分かるでしょうか？

**Comment by crohas** [comment]
私の方でも必ず発生するわけではありませんが、発生するときは PNG 等の画像ファイルで発生していたと記憶しています。
当時のログが残っていないので、再発次第追記します。

**Comment by crohas** [comment]
再発自体は何度かしているのですが、発生条件はわかりませんでした。
